### PR TITLE
Updating test package version to 0.17.1

### PR DESCRIPTION
**Pull request by arnaudelub**
Can you please merge this PR and publish the release version of dartz to pub?
the test plugin version has been changed to the released version and flutter test runs correctly:
```bash
flutter test
Changing current working directory to: /home/idelub/Repository/Flutter/forks/dartz
Running "flutter pub get" in dartz...                              43.3s
00:02 +258: All tests passed!
```
Thanks

### CODE REVIEW

**Comment by spebbe** [comment]
Hi @arnaudelub! Thanks for the PR! Would you be OK with targeting `0.10.0-nullsafety.2` instead of `0.10.0`, since I'm not ready to commit the main track to require 2.12+ just yet?

**Comment by arnaudelub** [comment]
Hi @spebbe, well it's your package, so it's up to you :)
But since you asked, and thank you for that, sure, don't worry, it's fine for me.
I'll wait for your plugin to be in release then, so i can publish mine in release as well as it depends on Dartz.

Thank you

**Comment by spebbe** [comment]
Maybe I'm misinterpreting you...? If you update the PR with dartz version changed from `0.10.0` to `0.10.0-nullsafety.2`, I would be happy to merge and release to pub! Would it be a blocker for you to depend on `0.10.0-nullsafety.2` in your package? Apologies if I completely misunderstood you :)

**Comment by arnaudelub** [comment]
yes, i guess there is a misunderstanding, probably mine.
Let's see, your branch *0_0_10_wip* already support null safety as the SDK is correctly set between **2.12.0 and 3.0.0**.
But the version **0.0.10** published on pub.dev has to be on pre-release because it depends on on a pre-released version of *test*.
That's why i made this PR, by updating the test package, your plugin on **pub.dev** can now be published as a release with the version **0.0.10**, at least it was my first guess.
But if you say you are not ready to publish your plugin as a Null Safety release version, it's fine to me, i can wait, there is no rush on my side.

**Comment by spebbe** [comment]
Ah, confusion cleared – thanks! Either way, the `test` dependency should be updated. If you make the suggested changes to your PR, you'll get contributor credz :) Otherwise, I can bump the package myself.

**Comment by arnaudelub** [comment]
ok sure, `0.10.0-nullsafety.2` it is then! i'll make the changes. Thanks

**Review by spebbe — APPROVED** [review]

**Comment by spebbe** [comment]
Published now – thanks again!

**Pull request merged**
