### PR TITLE
Added more function typedefs, made tuples const, added tuples 5-20

### PR DESCRIPTION
**Pull request by modulovalue**
- I needed the tuples to be const. I hope there's no issue around that with older dart versions.
- and I added a few more tuples. _(Extension methods make such large tuples very useful in certain cases I hope you don't mind them)_

I'd appreciate it if you could publish a version with these changes on pub.dev if you accept this PR.

Thanks.

Note: The editor folds were added to automatically collapse the data class sections in certain IDEs like Intellij.

### CODE REVIEW

**Comment by spebbe** [comment]
Looks fantastic! I'll look through it a bit more carefully and get back to you as soon as I can.

**Comment by spebbe** [comment]
Thank you for this! I think it looks great, but I have one request. Could you kill the `runtimeType == other.runtimeType` in the `==` overrides? I can't imagine that it would ever cause any practical change in semantics for tuples and any mention of `runtimeType` forces dart2js to reify generic type parameters, even when otherwise unnecessary. This results in a surprisingly large performance penalty in js at least. Not sure how it affects VM/Flutter performance though.

**Comment by modulovalue** [comment]
@spebbe done

**Comment by spebbe** [comment]
sweet!

**Comment by spebbe** [comment]
@modulovalue: 0.9.0-dev.2 published -- thanks again!

**Pull request merged**
